export const profBonus = { 1:2, 2:3, 3:4, 4:5, 5:6 }

export const abilities = [
    {
        id: 1,
        title: 'Strength',
        score: 10,
    },
    {
        id: 2,
        title: 'Dexterity',
        score: 10,
    },
    {
        id: 3,
        title: 'Constitution',
        score: 10,
    },
    {
        id: 4,
        title: 'Intelligence',
        score: 10,
    },
    {
        id: 5,
        title: 'Wisdom',
        score: 10,
    },
    {
        id: 6,
        title: 'Charisma',
        score: 10,
    }
]

export const skills = [
    {
        id: 1,
        name: "Acrobatics",
        ability: 2,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 2,
        name: "Animal Handling",
        ability: 5,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 3,
        name: "Arcana",
        ability: 4,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 4,
        name: "Athletics",
        ability: 1,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 5,
        name: "Deception",
        ability: 6,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 6,
        name: "History",
        ability: 4,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 7,
        name: "Insight",
        ability: 5,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 8,
        name: "Indimidation",
        ability: 6,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 9,
        name: "Investigation",
        ability: 5,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 10,
        name: "Medicine",
        ability: 5,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 11,
        name: "Nature",
        ability: 4,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 12,
        name: "Perception",
        ability: 5,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 13,
        name: "Performance",
        ability: 6,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 14,
        name: "Persuasion",
        ability: 6,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 15,
        name: "Religion",
        ability: 4,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 16,
        name: "Sleight of Hand",
        ability: 2,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 17,
        name: "Stealth",
        ability: 2,
        hasProf: false,
        hasExp: false,
    },
    {
        id: 18,
        name: "Survival",
        ability: 5,
        hasProf: false,
        hasExp: false,
    }
]

export const classes = {
    barbarian: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    },
    bard: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    cleric: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    druid: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    fighter: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    monk: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    paladin: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    ranger: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    rogue: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    sorcerer: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    warlock: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }, 
    wizard: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    }
}

export const modCalc = (x) => {
    const mod = Math.floor((x-10)/2);
    return mod
}

export const sign = (x) => {
    return x > 0 ? "+" + x : x;
}